### PR TITLE
Fix docker compose

### PR DESCRIPTION
**Pull request by ItayHoresh**
run pipert container with gpu

### CODE REVIEW

**Comment by ItayHoresh** [comment]
@ItamarWilf please check if it works on your computer before you merge it.
Update your docker-compose file to be like the file in this pr.

**Comment by ItamarWilf** [comment]
@ItayHoresh looks like it's still uses CPU...

**Comment by sionovd** [comment]
@ItayHoresh @ItamarWilf does the container have access to the GPU when you run it without docker-compose? For me it didn't, so I think the problem might be the base image

**Comment by rotemtzaban** [comment]
@sionovd you need to add --gpus=all to the docker run command to make it run on gpu.
An alternative to that, is using the old nvidia container runtime like [here](https://github.com/NVIDIA/nvidia-docker#upgrading-with-nvidia-docker2-deprecated).
I dont think you have to install the whole nvidia-docker package, only nvidia-container-runtime, and then add the runtime by editing the daemon.json as shown [here](https://github.com/NVIDIA/nvidia-container-runtime#daemon-configuration-file).

After this, you run with --runtime nvidia -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=all

**Comment by rotemtzaban** [comment]
The second way is deprecated, but it is the only way that currently works with either docker-compose or k8s, so i think it is the best way to work until the issues there are resolved.

**Pull request merged**
